# Appends get_args + is_candle_in_window + run_bot to bot_runner_multi.py

dst_path = 'D:/BotForex/src/bot_runner_multi.py'

lines = []
A = lines.append

# ===== get_args =====
A('')
A('')
A('def get_args():')
A('    """Parse command line arguments"""')
A('    parser = argparse.ArgumentParser(description="BotForex Multiple Master Candle Bot")')
A('')
A('    # Required')
A('    parser.add_argument("--strategy", type=str, required=True,')
A('                        help="Strategy ID (e.g., multiple_master_candle)")')
A('    parser.add_argument("--symbol", type=str, required=True,')
A('                        help="Trading symbol (e.g., XAUUSD)")')
A('    parser.add_argument("--user", type=str, required=True,')
A('                        help="Username for MT5 credentials")')
A('')
A('    # Window params (replaces --entry_time from bot_runner.py)')
A('    parser.add_argument("--window_start", type=str, required=True,')
A('                        help="Window start HH:MM (candle open times)")')
A('    parser.add_argument("--window_end", type=str, required=True,')
A('                        help="Window end HH:MM (exclusive, candle open times)")')
A('    parser.add_argument("--priority_direction", type=str, default="auto",')
A('                        choices=["BUY", "SELL", "auto"],')
A('                        help="Priority direction: BUY, SELL, or auto (first candle locks direction)")')
A('')
A('    # Optional parameters (override strategy defaults)')
A('    parser.add_argument("--lot_size", type=float, default=None)')
A('    parser.add_argument("--sl_pips", type=float, default=None)')
A('    parser.add_argument("--rr_ratio", type=float, default=None)')
A('    parser.add_argument("--max_candles", type=int, default=None)')
A('    parser.add_argument("--timeframe", type=str, default=None)')
A('    parser.add_argument("--entry_mode", type=str, default=None,')
A('                        choices=["close", "range_percent", "signal"])')
A('    parser.add_argument("--entry_percent", type=float, default=None)')
A('    parser.add_argument("--buffer_k", type=float, default=None)')
A('    parser.add_argument("--lot_mode", type=str, default=None,')
A('                        choices=["fixed", "flex"])')
A('    parser.add_argument("--starting_equity", type=float, default=None)')
A('    parser.add_argument("--risk_mode", type=str, default=None,')
A('                        choices=["percent", "amount", "fixed_amount"])')
A('    parser.add_argument("--risk_percent", type=float, default=None)')
A('    parser.add_argument("--risk_amount", type=float, default=None)')
A('    parser.add_argument("--risk_compounding", type=int, default=None)')
A('    parser.add_argument("--tp_type", type=str, default=None,')
A('                        choices=["price_based", "close_based"])')
A('    parser.add_argument("--sl_type", type=str, default=None,')
A('                        choices=["price_based", "close_based"])')
A('')
A('    # Move SL to Breakeven')
A('    parser.add_argument("--move_sl_to_breakeven", type=int, default=None)')
A('    parser.add_argument("--breakeven_trigger_percent", type=float, default=None)')
A('    parser.add_argument("--breakeven_target", type=str, default="entry")')
A('')
A('    # Pending order expiry (no retry logic in multi — failed placements skipped)')
A('    parser.add_argument("--pending_order_expire_candles", type=int, default=0,')
A('                        help="Cancel LIMIT if not filled after N candles (0=wait indefinitely)")')
A('')
A('    # Bot control')
A('    parser.add_argument("--test", type=int, default=1,')
A('                        help="Test mode: 1=test (no real trades), 0=live")')
A('    parser.add_argument("--interval", type=int, default=1,')
A('                        help="Check interval in seconds (default: 1)")')
A('')
A('    return parser.parse_args()')
A('')
A('')

# ===== is_candle_in_window =====
A('def is_candle_in_window(now: datetime, window_start: str, window_end: str, timeframe: str) -> bool:')
A('    """Check if a candle just closed within the window.')
A('')
A('    Window refers to candle OPEN times.')
A('    E.g., window 09:00-11:00 with M5: candles opening 09:00..10:55 close at 09:05..11:00.')
A('    A candle that just closed at time `now` has open_time = now - timeframe_minutes.')
A('    Returns True if open_time falls within [window_start, window_end).')
A('    """')
A('    tf_map = {')
A("        'M1': 1, 'M5': 5, 'M15': 15, 'M30': 30,")
A("        'H1': 60, 'H4': 240, 'D1': 1440")
A('    }')
A('    tf_mins = tf_map.get(timeframe, 5)')
A('')
A('    # Candle open time in total minutes from midnight')
A('    open_total = now.hour * 60 + now.minute - tf_mins')
A('')
A('    ws_h, ws_m = map(int, window_start.split(":"))')
A('    we_h, we_m = map(int, window_end.split(":"))')
A('    start_total = ws_h * 60 + ws_m')
A('    end_total = we_h * 60 + we_m')
A('')
A('    return start_total <= open_total < end_total')
A('')
A('')

with open(dst_path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('get_args + is_candle_in_window appended, lines:', open(dst_path).read().count('\n'))
